# Generated by Django 3.2.5 on 2021-08-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('button_stupid', models.BigIntegerField(blank=True, default=0, null=True)),
                ('button_fat', models.BigIntegerField(blank=True, default=0, null=True)),
                ('button_dumb', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
